Fixed parameter placeholders in translations
luyadev/luya pull request #2187
Opened 2024-01-08 17:02 UTC by hbugdoll

### What are you changing/introducing

Fixed parameter placeholders in Bulgarian, Hungarian and Romanian translations for `Yii::t()`.

### What is the reason for changing/introducing

Parameter placeholder names were accidentally translated, e.g. `{attribute}` &rarr; `{атрибутът}`.

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | –

2024-01-08 18:11 UTC, nadar commented
thanks!

2024-01-08 18:11 UTC, nadar requested changes
can you please add a change log entrie in core/CHANGELOG.md referring to this PR? Thanks

2024-01-08 23:52 UTC, hbugdoll commented
> can you please add a change log entrie in core/CHANGELOG.md referring to this PR? Thanks

Done.

2024-01-09 08:59 UTC, nadar approved these changes

2024-01-09 09:00 UTC, nadar commented
thanks! @hbugdoll

2024-01-09 09:00 UTC, merged